import yaml from "js-yaml";

/*
Convert workflow graph → Camel YAML DSL

This exporter produces a simple `restConfiguration`, a `rest` section for
`apiNode` nodes (grouped by path), and a `route` entry per API entrypoint.
Each route's `steps` are generated by walking outgoing edges and mapping node
types to Camel steps. The goal is to provide a useful, human-readable YAML
preview for canvas flows.
*/
export function workflowToCamelYAML(workflow) {
  const { nodes = [], edges = [] } = workflow || {};

  if (!nodes.length) return "";

  // Build lookup maps
  const nodeById = Object.fromEntries(nodes.map((n) => [n.id, n]));
  const outgoing = {};
  edges.forEach((e) => {
    if (!outgoing[e.source]) outgoing[e.source] = [];
    outgoing[e.source].push(e.target);
  });

  // 1) restConfiguration (defaults)
  const restConfiguration = {
    restConfiguration: {
      component: "servlet",
      contextPath: "/camel",
      bindingMode: "auto",
    },
  };

  // 2) Build `rest` entries by grouping apiNodes by path
  const apiNodes = nodes.filter((n) => n.type === "apiNode");
  const restMap = {}; // path -> array of methods

  apiNodes.forEach((n) => {
    const path = n.data?.path || "/";
    const method = (n.data?.method || "get").toLowerCase();
    const produces = inferProduces(n);
    const to = `direct:${n.id}`;

    const params = buildRestParams(n);
    const consumes = n.data?.body ? "application/json" : undefined;

    if (!restMap[path]) restMap[path] = {};
    if (!restMap[path][method]) restMap[path][method] = [];

    restMap[path][method].push({ produces, to, nodeId: n.id, params, consumes });
  });

  const restArray = Object.entries(restMap).map(([path, methods]) => {
    const methodsArr = Object.entries(methods).map(([m, arr]) => {
      // support multiple entries for same method (rare) — keep them as list
      return [m, arr.map((entry) => ({ produces: entry.produces, to: entry.to }))];
    });

    // Convert to expected YAML shape: { path: <path>, get: [ ... ] }
    const restEntry = { path };
    methodsArr.forEach(([m, list]) => {
      restEntry[m] = list;
    });
    return restEntry;
  });

  // 3) Build routes: one route per apiNode (entrypoint) following outgoing edges
  const routes = apiNodes.map((entry) => {
    const visited = new Set();
    const steps = [];

    // walk starting from entry, follow edges breadth-first along primary outgoing chain
    let stack = [entry.id];
    while (stack.length) {
      const currentId = stack.shift();
      if (!currentId || visited.has(currentId)) continue;
      visited.add(currentId);

      const node = nodeById[currentId];
      if (!node) continue;

      // skip the starting apiNode itself for steps (it's the from endpoint)
      if (node.id !== entry.id) {
        const mapped = mapNodeToCamelStep(node);
        if (mapped) steps.push(mapped);
      }

      const outs = outgoing[currentId] || [];
      // add outgoing targets to queue
      outs.forEach((t) => {
        if (!visited.has(t)) stack.push(t);
      });
    }
    // Prepend configuration steps for headers, query/path params, and body
    const configSteps = buildConfigSteps(entry);

    return {
      route: {
        id: sanitizeRouteId(entry),
        from: {
          uri: `direct:${entry.id}`,
          steps: [...configSteps, ...steps],
        },
      },
    };
  });

  // Finally assemble YAML top-level array: restConfiguration, rest (one per path), routes
  const yamlDoc = [];
  yamlDoc.push(restConfiguration);

  // push rest entries
  restArray.forEach((r) => yamlDoc.push({ rest: r }));

  // push routes
  routes.forEach((rt) => yamlDoc.push(rt));

  return yaml.dump(yamlDoc, { noRefs: true });
}

function inferProduces(node) {
  // basic heuristic: if body present and content-like, produce JSON, else text/plain
  const body = node.data?.body;
  if (body && typeof body === "object") return "application/json";
  return "text/plain";
}

function buildRestParams(node) {
  const params = [];
  const qp = node.data?.queryParams || {};
  const pp = node.data?.pathParams || {};

  Object.keys(pp).forEach((name) => {
    params.push({ name, type: "path", required: true });
  });

  Object.keys(qp).forEach((name) => {
    // allow qp[name] to be an object with required/type
    const meta = qp[name] || {};
    params.push({ name, type: meta.type || "query", required: !!meta.required });
  });

  if (node.data?.body) {
    params.push({ name: "body", type: "body", required: true });
  }

  return params.length ? params : undefined;
}

function buildConfigSteps(node) {
  const steps = [];

  // map known headers to setHeader steps
  const headers = node.data?.headers || {};
  Object.keys(headers).forEach((name) => {
    steps.push({ setHeader: { name, simple: `
${"${header." + name + "}"}` } });
  });

  // map path/query params to properties for later use
  const qp = node.data?.queryParams || {};
  const pp = node.data?.pathParams || {};

  Object.keys(pp).forEach((name) => {
    steps.push({ setProperty: { name, simple: `
${"${header." + name + "}"}` } });
  });
  Object.keys(qp).forEach((name) => {
    steps.push({ setProperty: { name, simple: `
${"${header." + name + "}"}` } });
  });

  // if body exists, capture it as property `requestBody`
  if (node.data?.body) {
    steps.push({ setProperty: { name: "requestBody", simple: "${body}" } });
  }

  return steps;
}

/*
Map node type → Camel processor
*/
function mapNodeToCamelStep(node) {
  if (!node || !node.type) return null;

  switch (node.type) {
    case "log":
      return { log: { message: node.data?.message || "info" } };

    case "http":
      return { to: node.data?.url };

    case "transform":
      return {
        setBody: {
          constant: node.data?.value ?? "",
        },
      };

    case "choice":
      return {
        choice: {
          when: node.data?.conditions || [],
        },
      };

    case "to":
      return { to: node.data?.uri };

    case "apiNode":
      // apiNodes typically act as entrypoints — represent them as a log for visibility
      return { log: { message: `Incoming ${node.data?.method || "GET"} ${node.data?.path || ""}` } };

    default:
      return null;
  }
}

function sanitizeRouteId(node) {
  const id = node?.id || "route";
  // ensure id is a simple string without spaces
  return id.replace(/[^a-zA-Z0-9-_]/g, "-");
}